
-- Grab Columns
SELECT 
		c.TABLE_NAME, c.COLUMN_NAME, c.DATA_TYPE, 
		c.IS_NULLABLE, c.COLUMN_KEY, c.COLUMN_TYPE 
	FROM 
		information_schema.TABLES t
			JOIN information_schema.COLUMNS c 
				ON c.TABLE_NAME = t.TABLE_NAME AND c.TABLE_SCHEMA='sakila'  
	WHERE 
		t.TABLE_SCHEMA='sakila' AND t.TABLE_TYPE='BASE TABLE'
;

-- Grab Foreign Keys
SELECT 
		CONSTRAINT_NAME, TABLE_NAME, COLUMN_NAME, 
		REFERENCED_TABLE_NAME, REFERENCED_COLUMN_NAME 
	FROM 
		information_schema.KEY_COLUMN_USAGE 
	WHERE 
		TABLE_SCHEMA='sakila' AND 
		REFERENCED_TABLE_NAME IS NOT NULL
;
